[package]
name = "solarscuffle-bot/springutil"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "A spring utility module derived from Fusion's springs, made to mimic the api and behavior of TweenService."

[dependencies]
